export const patientdata = {
    "resourceType" : "Patient",
    "meta" : {
        "profile" : [ 
            "http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-PersonOfRecord"
        ]
    },
    "text" : {
        "status" : "generated",
        "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>. Version identifier: 4d02400401b9fab839e47bf5b2f1f6a8c683ab55</div>"
    },
    "extension" : [ 
        {
            "url" : "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "valueCodeableConcept" : {
                "coding" : [ 
                    {
                        "system" : "http://hl7.org/fhir/v3/Race",
                        "code" : "2028-9",
                        "display" : "Asian"
                    }
                ],
                "text" : "race"
            }
        }, 
        {
            "url" : "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "valueCodeableConcept" : {
                "coding" : [ 
                    {
                        "system" : "http://hl7.org/fhir/v3/Ethnicity",
                        "code" : "2186-5",
                        "display" : "Nonhispanic"
                    }
                ],
                "text" : "ethnicity"
            }
        }, 
        {
            "url" : "http://hl7.org/fhir/StructureDefinition/birthPlace",
            "valueAddress" : {
                "city" : "Lynn",
                "state" : "MA",
                "country" : "US"
            }
        }, 
        {
            "url" : "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString" : "Jocelyn772 Bartell415"
        }, 
        {
            "url" : "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode" : "F"
        }, 
        {
            "url" : "http://hl7.org/fhir/StructureDefinition/patient-interpreterRequired",
            "valueBoolean" : false
        }, 
        {
            "url" : "http://standardhealthrecord.org/fhir/StructureDefinition/shr-actor-FictionalPerson-extension",
            "valueBoolean" : true
        }, 
        {
            "url" : "http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-FathersName-extension",
            "valueHumanName" : {
                "text" : "Enos147 McClure754"
            }
        }, 
        {
            "url" : "http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-SocialSecurityNumber-extension",
            "valueString" : "999-40-4690"
        }
    ],
    "identifier" : [ 
        {
            "system" : "https://github.com/synthetichealth/synthea",
            "value" : "697effc5-2dde-4d83-9ee1-afef42dcb77c"
        }, 
        {
            "type" : {
                "coding" : [ 
                    {
                        "system" : "http://hl7.org/fhir/identifier-type",
                        "code" : "SB"
                    }
                ]
            },
            "system" : "http://hl7.org/fhir/sid/us-ssn",
            "value" : "999404690"
        }, 
        {
            "type" : {
                "coding" : [ 
                    {
                        "system" : "http://hl7.org/fhir/v2/0203",
                        "code" : "DL"
                    }
                ]
            },
            "system" : "urn:oid:2.16.840.1.113883.4.3.25",
            "value" : "S99964273"
        }
    ],
    "name" : [ 
        {
            "use" : "official",
            "family" : "Abbott",
            "given" : [ 
                "Adrianna134"
            ],
            "prefix" : [ 
                "Mrs."
            ]
        }, 
        {
            "use" : "maiden",
            "family" : "McClure754",
            "given" : [ 
                "Adrianna134"
            ]
        }
    ],
    "telecom" : [ 
        {
            "system" : "phone",
            "value" : "(628) 807-1017",
            "use" : "home"
        }
    ],
    "gender" : "female",
    "birthDate" : "1959-10-19",
    "address" : [ 
        {
            "extension" : [ 
                {
                    "url" : "http://hl7.org/fhir/StructureDefinition/geolocation",
                    "extension" : [ 
                        {
                            "url" : "latitude",
                            "valueDecimal" : 42.17814942639
                        }, 
                        {
                            "url" : "longitude",
                            "valueDecimal" : -71.0774036999588
                        }
                    ]
                }
            ],
            "line" : [ 
                "2423 Beier Port", 
                "Apt. 290"
            ],
            "city" : "Randolph",
            "state" : "MA",
            "postalCode" : "02368",
            "country" : "US"
        }
    ],
    "maritalStatus" : {
        "coding" : [ 
            {
                "system" : "http://hl7.org/fhir/v3/MaritalStatus",
                "code" : "M"
            }
        ],
        "text" : "M"
    },
    "multipleBirthBoolean" : false,
    "communication" : [ 
        {
            "language" : {
                "coding" : [ 
                    {
                        "system" : "http://hl7.org/fhir/ValueSet/languages",
                        "code" : "zh",
                        "display" : "Chinese"
                    }
                ]
            }
        }
    ]
}